import requests
import ipaddress
from datetime import datetime, timezone

COUNTRY = "IR"
OUTPUT = "iran_ipv4.rsc"

EXTRA_PREFIXES = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
]


def fetch_ripe(country):
    url = (
        "https://stat.ripe.net/data/country-resource-list/data.json"
        f"?resource={country}&v4_format=prefix"
    )

    try:
        print("Fetching RIPE...")
        r = requests.get(url, timeout=60)
        r.raise_for_status()

        data = r.json()

        prefixes = set(
            data.get("data", {})
                .get("resources", {})
                .get("ipv4", [])
        )

        print(f"RIPE: {len(prefixes)} prefixes")
        return prefixes

    except Exception as e:
        print(f"RIPE failed: {e}")
        return set()


def fetch_ipdeny():
    url = "https://www.ipdeny.com/ipblocks/data/aggregated/ir-aggregated.zone"

    try:
        print("Fetching IPDeny...")
        r = requests.get(url, timeout=60)
        r.raise_for_status()

        prefixes = set()

        for line in r.text.splitlines():
            line = line.strip()

            if not line:
                continue

            if line.startswith("#"):
                continue

            prefixes.add(line)

        print(f"IPDeny: {len(prefixes)} prefixes")
        return prefixes

    except Exception as e:
        print(f"IPDeny failed: {e}")
        return set()


def validate_prefixes(prefixes):
    nets = []

    for prefix in prefixes:
        try:
            nets.append(
                ipaddress.ip_network(prefix, strict=False)
            )
        except Exception:
            pass

    return nets


def main():

    print("======================================")
    print("Iran MikroTik GeoIP Generator")
    print("Sources: RIPE + IPDeny")
    print("======================================")
    print()

    prefixes = set()

    # RIPE
    prefixes.update(fetch_ripe(COUNTRY))

    # IPDeny
    prefixes.update(fetch_ipdeny())

    # Local/private networks
    prefixes.update(EXTRA_PREFIXES)

    print()
    print(f"Raw unique prefixes: {len(prefixes)}")

    nets = validate_prefixes(prefixes)

    # Collapse overlapping networks
    nets = list(ipaddress.collapse_addresses(nets))

    nets.sort(
        key=lambda x: (
            int(x.network_address),
            x.prefixlen
        )
    )

    now = datetime.now(timezone.utc)

    with open(OUTPUT, "w", encoding="utf-8") as f:

        f.write("# ==================================================\n")
        f.write("# Iran IPv4 List for MikroTik\n")
        f.write("# Sources:\n")
        f.write("#   - RIPE NCC Country Resource List\n")
        f.write("#   - IPDeny Aggregated Country List\n")
        f.write("# Generated by Hossein Golshan\n")
        f.write(f"# Date (UTC): {now:%Y-%m-%d %H:%M:%S}\n")
        f.write(f"# Total Prefixes: {len(nets)}\n")
        f.write("# ==================================================\n\n")

        f.write("/ip firewall address-list\n\n")

        # Clean existing list
        f.write('remove [find where list="IR"]\n')
        f.write(':delay 1\n\n')

        for net in nets:
            f.write(
                f'add address={net} list=IR comment="Iran GeoIP"\n'
            )

    print()
    print("Done.")
    print(f"Generated file: {OUTPUT}")
    print(f"Final prefixes: {len(nets)}")


if __name__ == "__main__":
    main()