import requests
import ipaddress
from datetime import datetime, timezone

COUNTRY = "IR"
OUTPUT = "iran_ipv4.rsc"

EXTRA_PREFIXES = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
]


def fetch_ripe(country):
    url = (
        "https://stat.ripe.net/data/country-resource-list/data.json"
        f"?resource={country}&v4_format=prefix"
    )

    try:
        r = requests.get(url, timeout=60)
        r.raise_for_status()
        data = r.json()

        return set(
            data.get("data", {})
                .get("resources", {})
                .get("ipv4", [])
        )

    except Exception as e:
        print("RIPE fetch failed:", e)
        return set()


def main():
    print("Fetching RIPE data...")

    prefixes = fetch_ripe(COUNTRY)

    if not prefixes:
        print("Warning: RIPE returned empty data. Using only local prefixes.")

    # Add extra safe networks
    for p in EXTRA_PREFIXES:
        prefixes.add(p)

    # Validate + normalize
    nets = []
    for p in prefixes:
        try:
            nets.append(ipaddress.ip_network(p, strict=False))
        except Exception:
            pass

    nets = list(ipaddress.collapse_addresses(nets))

    nets.sort(key=lambda x: (int(x.network_address), x.prefixlen))

    now = datetime.now(timezone.utc)

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("# ==================================================\n")
        f.write("# Iran IP List for MikroTik\n")
        f.write("# Source: RIPE Country Resource List\n")
        f.write("# Generated by Hossein Golshan\n")
        f.write(f"# Date (UTC): {now}\n")
        f.write(f"# Total prefixes: {len(nets)}\n")
        f.write("# ==================================================\n\n")

        f.write("/ip firewall address-list\n\n")
        f.write('remove [find where list="IR"]\n')
        f.write(":delay 1\n\n")

        for n in nets:
            f.write(
                f'add address={n} list=IR comment="IR GeoIP"\n'
            )

    print("Generated:", OUTPUT)
    print("Total prefixes:", len(nets))


if __name__ == "__main__":
    main()