import requests
import ipaddress
from datetime import datetime, timezone

COUNTRY = "IR"
OUTPUT = "iran_ipv4.rsc"

EXTRA_PREFIXES = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
]

def fetch_ripe(country):
    url = (
        "https://stat.ripe.net/data/country-resource-list/data.json"
        f"?resource={country}&v4_format=prefix"
    )

    r = requests.get(url, timeout=60)
    r.raise_for_status()

    data = r.json()
    return set(data["data"]["resources"]["ipv4"])


def main():
    print("Fetching RIPE data...")

    prefixes = fetch_ripe(COUNTRY)

    for p in EXTRA_PREFIXES:
        prefixes.add(p)

    nets = [ipaddress.ip_network(p, strict=False) for p in prefixes]
    nets = list(ipaddress.collapse_addresses(nets))

    nets.sort(key=lambda x: (int(x.network_address), x.prefixlen))

    now = datetime.now(timezone.utc)

    with open(OUTPUT, "w") as f:
        f.write("# ==================================================\n")
        f.write("# Iran IP List for MikroTik\n")
        f.write("# Source: RIPE Country Resource List\n")
        f.write("# Generated by Hossein Golshan\n")
        f.write(f"# Date: {now}\n")
        f.write(f"# Total: {len(nets)}\n")
        f.write("# ==================================================\n\n")

        f.write("/ip firewall address-list\n\n")
        f.write('remove [find where list="IR"]\n\n')

        for n in nets:
            f.write(f'add address={n} list=IR comment="IR GeoIP"\n')

    print("Generated:", OUTPUT)


if __name__ == "__main__":
    main()